title: "Irshad â€“ Research Website"
description: "Beamline Scientist | Elettra-Sincrotrone Trieste | High-Pressure XRD | Synchrotron Methods"
theme: null
markdown: kramdown

# Contact Information
email_primary: "irshad.kariyattuparamb@elettra.eu"
email_secondary: "ikariyat@ictp.it"

mobile_primary: "+39-040-375-8051"
mobile_secondary: "+39-040-375-8434"

github: "https://github.com/irshadka17"
linkedin: "https://it.linkedin.com/in/irshad-k-a-359a53103"
orcid: "https://orcid.org/0000-0002-2790-6430"
researchgate: "https://www.researchgate.net/profile/Irshad-K-A"


