title: "Irshad â€“ Research Website"

description: |
  Scientist (IISc/ICTP)
  High pressure diffraction beamline: Xpress
  Elettra Sincrotrone Trieste S.C.p.A.
  S.S. 14 Km 163,5 in Area Science Park
  34149 Basovizza, Trieste, Italy

theme: null
markdown: kramdown

# Contact Information
email_primary: "irshad.kariyattuparamb@elettra.eu"
email_secondary: "ikariyat@ictp.it"

mobile_primary: "+39-040-375-8051 (office)"
mobile_secondary: "+39-040-375-8434 (beamline)"

github: "https://github.com/irshadka17"
googlescholar: "https://scholar.google.com/citations?hl=en&user=3aPgewgAAAAJ&view_op=list_works&sortby=pubdate"
linkedin: "https://it.linkedin.com/in/irshad-k-a-359a53103"
orcid: "https://orcid.org/0000-0002-2790-6430"
researchgate: "https://www.researchgate.net/profile/Irshad-K-A"






